core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from.import views
from.forms import LoginForm

app_name='core'

urlpatterns = [
    path('',views.index,name='index'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core\login.html',authentication_form=LoginForm),name='login'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
      username=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your Username',
        'class':'w-full py-4 px-6 rounded-xl'


    }) )
      password=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Repeat password',
        'class':'w-full py-4 px-6 rounded-xl'


    }) )      


class SignupForm(UserCreationForm):
    class Meta:
        model=User
        fields=('username','email','password1','password2')
    username=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your Username',
        'class':'w-full py-4 px-6 rounded-xl'


    }) )
    email=forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'Your email adress',
        'class':'w-full py-4 px-6 rounded-xl'


    }) )
    
    password1=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password',
        'class':'w-full py-4 px-6 rounded-xl'


    }) )   
    
    password2=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Repeat password',
        'class':'w-full py-4 px-6 rounded-xl'


    }) )      

core/views.py
from django.shortcuts import render, redirect
from item.models import Category,Item

from.forms import SignupForm
# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })
    
def contact(request):
    return render(request,'core/contact.html')

def signup(request):
    if request.method=="POST":
        form=SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:    
        form=SignupForm()

    return render(request,'core/signup.html',{

        'form':form
    })

core/templates/core/base.html
<!DOCTYPE html>
<html>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <title>{% block title %} {% endblock %} | CompareShop</title>
    </head>
    <body class="bg-gray-100 text-gray-800">
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200 bg-white shadow-md">
            <a href="/" class="text-2xl font-bold text-teal-600">CompareShop</a>
            <div class="space-x-6">
                {% comment %} <a href="{% url 'item:new' %}" class="text-lg font-semibold text-gray-700 hover:text-gray-500">New Item</a> {% endcomment %}
                <a href="{% url 'item:items' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-lg hover:bg-teal-700">Browse</a>
                {% if request.user.is_authenticated %}
{% comment %}                     <a href="{% url 'item:items' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-lg hover:bg-teal-700">Browse</a> {% endcomment %}
        {% comment %}             <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-lg hover:bg-gray-700">Dashboard</a> {% endcomment %}
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-lg hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-lg hover:bg-gray-700">Log in</a>
             
                {% endif %}
            </div>
        </nav>
        <div class="px-6 py-6">
            {% block content %} 
            {% endblock %}
        </div>
        <footer class="py-6 px-6 flex justify-between items-center bg-gray-800 text-gray-400">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold">About</h3>
                <p class="text-lg text-gray-300">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold">Menu</h3>
                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-300">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-300">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-300">Privacy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-300">Terms of use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html'%}
{%block title%} Contact {% endblock  %}
{%block content%}
    <h1>Contact Page</h1>
{%endblock%}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %} Welcome {% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-3xl font-bold text-center text-teal-600">Newest Items</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {% for item in items %}
        <div class="bg-white rounded-xl shadow-md overflow-hidden transform transition duration-300 hover:scale-105">
            <a href="{% url 'item:detail' item.id %}">
                <div class="h-48">
                    {% if item.image %}
                    <img src="{{ item.image.url }}" class="w-full h-full object-contain">
                    {% endif %}
                </div>
                <div class="p-6">
                    <h2 class="text-2xl font-semibold">{{ item.name }}</h2>
                    <p class="text-gray-500 mt-2">Price: {{ item.price }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-3xl font-bold text-center text-teal-600">Categories</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {% for category in categories %}
        <div class="bg-white rounded-xl shadow-md overflow-hidden transform transition duration-300 hover:scale-105">
            <a href="#">
                <div class="p-6">
                    <h2 class="text-2xl font-semibold">{{ category.name }}</h2>
                    <p class="text-gray-500 mt-2">{{ category.items.count }} items</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label></br>
            {{form.username}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label></br>
            {{form.password}}
        </div>
        
       
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-5 bg-red-100 rounded-xl">
            {% for field in form %}
                {{field.errors}}
            {% endfor %}   
            
             {{ form.non_field_errors }}
        </div>
        {% endif %}
       {% comment %}  {{ form.as_p }} {% endcomment %}
        <button class="py-4 px-8 text-lf bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Subbmit</button>
    </form>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign Up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label></br>
            {{form.username}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Email</label></br>
            {{form.email}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label></br>
            {{form.password1}}
        </div>
        
        <div class="mb-3">
            <label class="inline-block mb-2">Repeat Password</label></br>
            {{form.password2}}
        </div>
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-5 bg-red-100 rounded-xl">
            {% for field in form %}
                {{field.errors}}
            {% endfor %}   
            
             {{ form.non_field_errors }}
        </div>
{% endif %}
       {% comment %}  {{ form.as_p }} {% endcomment %}
        <button class="py-4 px-8 text-lf bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Subbmit</button>
    </form>
</div>
{% endblock %}