item/urls.py
from django.urls import path
from.import views 
from.views import detail, add_review, edit_review_view
from .views import edit_review

app_name='item'

urlpatterns=[
    path('',views.items,name='items'),
    path('new/',views.new,name='new'),
    path('<int:pk>/',views.detail,name='detail'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/edit/',views.edit,name='edit'),
    path('item/<int:pk>/', detail, name='item_detail'),
    path('item/<int:pk>/add_review/', add_review, name='add_review'),
    path('review/edit/<int:pk>/', edit_review_view, name='edit_review_view'),
    path('edit-review/<int:review_id>/', edit_review, name='edit_review'),  
    path('items/', views.items, name='items'),
]

item/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Marketplace(models.Model):
    name = models.CharField(max_length=255)
    api_url = models.URLField(default='http://127.0.0.1:8080/api/products/')
    url = models.URLField(default='http://127.0.0.1:8080')
    token = models.CharField(max_length=100, default='sda')
    is_active = models.BooleanField(default=False) 

    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField(null=True, blank=True)
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    average_rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.name

    def update_average_rating(self):
        # Получение среднего рейтинга с маркетплейсов
        marketplace_ratings = self.marketplaces.all()
        if marketplace_ratings.exists():
            average_rating = marketplace_ratings.aggregate(models.Avg('marketplace_rating'))['marketplace_rating__avg']
            self.average_rating = average_rating
            self.save()
        else:
            self.average_rating = None
            self.save()

class ItemMarketplace(models.Model):
    item = models.ForeignKey(Item, related_name='marketplaces', on_delete=models.CASCADE)
    marketplace = models.ForeignKey(Marketplace, related_name='items', on_delete=models.CASCADE)
    marketplace_rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return f"{self.item.name} at {self.marketplace.name}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.item.update_average_rating()

    def delete(self, *args, **kwargs):
        item = self.item  #Saving link on item before delt
        super().delete(*args, **kwargs)
        item.update_average_rating()

class Review(models.Model):
    item = models.ForeignKey(Item, related_name='reviews', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='reviews', on_delete=models.CASCADE)
    comment = models.TextField()
    rating = models.IntegerField(default=1, choices=[(i, i) for i in range(1, 6)])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}'s review of {self.item.name}"

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<script>
    function toggleEditForm(reviewId) {
        var form = document.getElementById('edit-form-' + reviewId);
        var comment = document.getElementById('review-comment-' + reviewId);
        if (form.classList.contains('hidden')) {
            form.classList.remove('hidden');
            comment.classList.add('hidden');
        } else {
            form.classList.add('hidden');
            comment.classList.remove('hidden');
        }
    }
</script>
<div class="grid grid-cols-1 lg:grid-cols-5 gap-6">
    <div class="col-span-3">
        {% if item.image %}
        <div class="flex items-center justify-center bg-gray-200 rounded-xl p-4">
            <img src="{{ item.image.url }}" class="max-h-64 object-contain">
        </div>
        {% endif %}
        {% if item.description %}
        <div class="mt-4 p-4 bg-white rounded-xl">
            <p class="text-gray-700">
                <strong class="text-gray-500">Description:</strong><br>
                {{ item.description }}
            </p>
        </div>
        {% endif %}
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl font-bold">{{ item.name }}</h1>
        <p class="text-gray-500"><strong>Price:</strong> {{ item.price }}</p>
        {% if item.average_rating %}
        <p class="text-gray-500"><strong>Average Rating:</strong> {{ item.average_rating }}</p>
        {% endif %}
        {% if item.category %}
        <p class="text-gray-500"><strong>Category:</strong> {{ item.category }}</p>
        {% endif %}

        {% if request.user == item.created_by %}
        <div class="my-6 p-6 bg-white rounded-xl">
            <p>This is your item</p>
            <a href="{% url 'item:edit' item.id %}" class="inline-block mt-4 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
            <a href="{% url 'item:delete' item.id %}" class="inline-block mt-4 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
        </div>
        {% else %}
        <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact seller</a>
        {% endif %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center font-bold">Marketplace Ratings</h2>
    <div class="space-y-4">
        {% for item_marketplace in item_marketplaces %}
        <div class="bg-white p-4 rounded-xl shadow">
            <p><strong>{{ item_marketplace.marketplace.name }}</strong></p>
            <p>Rating: {{ item_marketplace.marketplace_rating }}</p>
            <p>Price: {{ item_marketplace.price }}</p>
        </div>
        {% endfor %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center font-bold">Related items</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {% for item in related_items %}
        <div class="bg-white rounded-xl shadow-md overflow-hidden transform transition duration-300 hover:scale-105">
            <a href="{% url 'item:detail' item.id %}">
                <div class="flex items-center justify-center h-32 bg-gray-200">
                    {% if item.image %}
                    <img src="{{ item.image.url }}" class="w-full h-full object-contain">
                    {% endif %}
                </div>
                <div class="p-6">
                    <h2 class="text-2xl font-semibold">{{ item.name }}</h2>
                    <p class="text-gray-500 mt-2">Price: {{ item.price }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% for review in reviews %}
<div class="w-full mx-auto bg-white rounded-xl shadow-md overflow-hidden my-4">
    <div class="p-4">
        <div class="flex justify-between items-center">
            <div class="uppercase tracking-wide text-sm text-indigo-500 font-semibold">Rating: {{ review.rating }}/5</div>
            {% if user.is_authenticated and user == review.user %}
            <button onclick="toggleEditForm('{{ review.id }}')" class="text-gray-500 hover:text-gray-700">Edit</button>
            {% endif %}
        </div>
        <p id="review-comment-{{ review.id }}" class="block mt-1 text-lg leading-tight font-medium text-black text-left">{{ review.comment }}</p>
        <p class="mt-2 text-gray-500">Reviewed by {{ review.user.username }}</p>

        <!-- Скрытая форма редактирования -->
        <div id="edit-form-{{ review.id }}" class="hidden">
            <form action="{% url 'item:edit_review' review.id %}" method="POST">
                {% csrf_token %}
                <textarea name="comment" class="w-full p-2 text-gray-700 border rounded-lg focus:outline-none" rows="4">{{ review.comment }}</textarea>
                <label for="rating" class="block mt-2 text-gray-700">Rating:</label>
                <select id="rating" name="rating" class="shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                    <option value="1" {% if review.rating == 1 %}selected{% endif %}>1</option>
                    <option value="2" {% if review.rating == 2 %}selected{% endif %}>2</option>
                    <option value="3" {% if review.rating == 3 %}selected{% endif %}>3</option>
                    <option value="4" {% if review.rating == 4 %}selected{% endif %}>4</option>
                    <option value="5" {% if review.rating == 5 %}selected{% endif %}>5</option>
                </select>
                <button type="submit" class="mt-2 px-4 py-2 bg-blue-500 text-white rounded-lg">Save</button>
            </form>
        </div>
    </div>
</div>
{% endfor %}

{% if user.is_authenticated %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form method="post" class="mt-8">
    {% csrf_token %}
    <div class="mb-4">
        <label for="id_comment" class="block text-gray-700 text-sm font-bold mb-2">Your Comment:</label>
        <textarea id="id_comment" name="comment" rows="4" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"></textarea>
    </div>
    <div class="mb-6">
        <label for="id_rating" class="block text-gray-700 text-sm font-bold mb-2">Your Rating:</label>
        <select id="id_rating" name="rating" class="shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
        </select>
    </div>
    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Submit Review</button>
</form>
{% else %}
<button onclick="location.href='{% url 'core:login' %}?next={{ request.path }}'" class="bg-blue-500 my-2 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded focus:outline-none focus:shadow-outline">Log in to leave a review</button>
<p>Please <a href="{% url 'core:login' %}?next={{ request.path }}" class="text-blue-500 hover:text-blue-700">log in</a> to leave a review.</p>
{% endif %}

{% endblock %}

item/templates/item/form.html
{%extends 'core/base.html' %}

{% block title %}{{title}}{% endblock %}

{%block content%}

<h1 class="mb-6 text-3xl">{{title}}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class ="space-y-4">
        {{form.as_p}}
    </div>
    {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-5 bg-red-100 rounded-xl">
        {% for field in form %}
            {{field.errors}}
        {% endfor %}   
        
         {{ form.non_field_errors }}
    </div>
    {% endif %}
    <button class="mt-6 py-4 px-8 text-lf bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Subbmit</button>
    </form>
{%endblock%}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}Items{% endblock %}

{% block content %}
<div class="grid grid-cols-1 lg:grid-cols-4 gap-4 pb-6">
    <div class="col-span-1 bg-gray-100 p-6 rounded-xl">
        <!-- Содержимое сайдбара -->
        <form method="get" action="{% url 'item:items' %}">
            <input name="query" class="w-full py-2 px-4 border rounded-xl" type="text" value="{{ query }}" placeholder="Find and buy">
            <button class="mt-2 py-2 px-4 text-lg bg-teal-500 text-white rounded-xl w-full">Search</button>
        </form>
        <hr class="my-6">
        <p class="font-semibold text-lg">Categories</p>
        <ul class="space-y-2">
            {% for category in categories %}
            <li class="py-2 px-2 rounded-xl {% if category.id == category_id %} bg-gray-200 {% endif %}">
                <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}" class="text-teal-600 hover:text-teal-800">{{ category.name }}</a>
            </li>
            {% endfor %}
        </ul>
        <hr class="my-6">
        <p class="font-semibold text-lg">Clear filters</p>
        <ul>
            <li><a href="{% url 'item:items' %}" class="mt-2 py-2 px-4 inline-block bg-yellow-500 rounded-xl text-white">Clear</a></li>
        </ul>
    </div>
    <div class="col-span-3">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {% for item in items %}
            <div class="bg-white rounded-xl shadow-md overflow-hidden transform transition duration-300 hover:scale-105">
                <a href="{% url 'item:detail' item.id %}">
                    <div class="flex items-center justify-center h-48 bg-gray-200">
                        {% if item.image %}
                        <img src="{{ item.image.url }}" class="w-full h-full object-contain">
                        {% endif %}
                    </div>
                    <div class="p-6">
                        <h2 class="text-2xl font-semibold">{{ item.name }}</h2>
                        <p class="text-gray-500 mt-2">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
        <div class="mt-6">
            <nav class="flex justify-center">
                <ul class="inline-flex items-center -space-x-px">
                    {% if items.has_previous %}
                    <li>
                        <a href="?page=1{% if query %}&query={{ query }}{% endif %}{% if category_id %}&category={{ category_id }}{% endif %}" class="px-3 py-2 ml-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700">First</a>
                    </li>
                    <li>
                        <a href="?page={{ items.previous_page_number }}{% if query %}&query={{ query }}{% endif %}{% if category_id %}&category={{ category_id }}{% endif %}" class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700">Previous</a>
                    </li>
                    {% endif %}
                    {% for num in items.paginator.page_range %}
                    {% if items.number == num %}
                    <li>
                        <a class="px-3 py-2 leading-tight text-blue-600 bg-blue-50 border border-blue-300">{{ num }}</a>
                    </li>
                    {% elif num > items.number|add:'-3' and num < items.number|add:'3' %}
                    <li>
                        <a href="?page={{ num }}{% if query %}&query={{ query }}{% endif %}{% if category_id %}&category={{ category_id }}{% endif %}" class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700">{{ num }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}
                    {% if items.has_next %}
                    <li>
                        <a href="?page={{ items.next_page_number }}{% if query %}&query={{ query }}{% endif %}{% if category_id %}&category={{ category_id }}{% endif %}" class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700">Next</a>
                    </li>
                    <li>
                        <a href="?page={{ items.paginator.num_pages }}{% if query %}&query={{ query }}{% endif %}{% if category_id %}&category={{ category_id }}{% endif %}" class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700">Last</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>

{% endblock %}